version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # Porta padrão para conexões AMQP
      - "15672:15672"  # Porta para acessar o painel de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência dos dados
      - rabbitmq_log:/var/log/rabbitmq   # Logs do RabbitMQ

volumes:
  rabbitmq_data:
  rabbitmq_log:
